version: '3'
services:
  api:
    build:
      context: finalApi/
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: playlist_api
    ports:
      - 3000:3000
    volumes:
    - api-data:/usr/src/uploads

volumes:
 api-data:
