version: '3.9'
services:
  api:
    build:
      context: ./finalApi
      dockerfile: Dockerfile
    restart: unless-stopped
    container_name: playlist_api
    privileged: true
    volumes:
      - uploads-imgs:/api/uploads
    ports:
      - 3000:3000

  app:
    image: stevencamsa/playlist:latest
    container_name: playlist_app
    ports:
     - 3301:81

